name: tests

on:
  push:
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test
        working-directory: frontend
        run: |
          export DISABLE_ESLINT_PLUGIN=true
          yarn install
          yarn build
